### ISSUE TITLE
Define for loop hmwk

### ISSUE THREAD

**Issue by ghost** [johnwfinigan/CSCI2467-Fall2015#10]
It has           size_t
                    strenln( ....., ........)

In us just defining or explaining the operations of the code, I do not see in the code size_t as a type to define a variable which will be used to accept the bytes returned from strenln
      ex.     size_t lengthOfString;
              lengthOfString = strenln(......., ........)

Question... in the code provided in the homework, where does the returned bytes go after invoking the function sternly ?

thanks.

**Comment by johnwfinigan** [comment]
If I understand right, you're asking, why is there not a named variable that holds the number that gets returned?

The last line of the function says `return (size_t)(cp - str)`

This reads as "cast the number resulting from (cp - str) to size_t and return it"

Essentially, the value being returned is anonymous, it doesn't correspond to a named variable. The rules of the language allow this because a function is only allowed to return one value, so you can just tell it to return a number and it will return that value.

So if you had a function called `add()` that adds numbers, you could say `int a = add(2,3)` and  `add()` would return the value 5, and that return value would get assigned to `a`.

What's going on at a lower level is that when you call return inside of a function, the value you're returning gets pushed to the stack in a known, defined place that the caller knows to look at after the function returns. Once it returns, the caller looks at that stack location and copies the value there to wherever it wants to.

Is that the kind of answer you're looking for?
