### ISSUE TITLE
Does read always write into buf[0]?

### ISSUE THREAD

**Issue by AmbyrShae** [johnwfinigan/CSCI2467-Fall2015#4]
Does read always write into first index [0] of a buffer? Or is that only the case with HW1?
Thanks

**Comment by johnwfinigan** [comment]
It just works out that way in HW1 due to the fact that buf is declared as an array, and the name of an array also serves as a pointer to the first element of the array. More specifically:

Read's prototype, from man 2 read:

```
ssize_t read(int fd, void * buf, size_t count);
```

The second argument, buf, is declared as a pointer with type void. Void is used here so that you can pass any type of pointer to read as buf, and internally to read it will be cast to some type that allows it to be written to one byte at a time (eg char *).

if we declare an array like 

```
char myarray[10];
```

and then call read like

```
read(f, myarray, 8);
```

we're just relying on the fact that myarray points to the memory address of myarray[0], and so read writes up to 8 bytes into the memory pointed to by myarray, which is a pointer with type char *. The data will be written starting at myarray[0].

but if we say:

```
read(f, myarray+1, 8) 
```

or

```
  read(f, &myarray[1], 8)
```

We're passing in a pointer to myarray[1], and up to 8 bytes will be written into the array, starting at myarray[1].

Helps?

**Comment by johnwfinigan** [comment]
Forgot to mention, Essential C section 3 on pointers and arrays should help here.

**Comment by AmbyrShae** [comment]
Yes, thank you.
