### ISSUE TITLE
Essential C - Regarding Arrays p. 16

### ISSUE THREAD

**Issue by ghost** [johnwfinigan/CSCI2467-Fall2015#5]
The name of the array refers to the whole array. (implementation) it works by representing a pointer to the start of the array ( from Essential C my questions come from this statement).

```
 question A: char greeting = 'h';
               How would one communicate this ? I would say, the variable greeting stores a char value of 'h' at address greeting[0].  Or would it be, the char value 'h' in the variable greeting is a pointer to a place in memory represented by greeting? 
```

How would one articulate char greeting = 'h'           and also           int greetings[6] = "hello"
Also, with greetings (not greeting), would the allocation of memory be 5 or 6, to take in hello (null terminator - hello is 5 letters, yet c adds a null terminator at end)?

Thanks.

**Comment by johnwfinigan** [comment]
The first one, I'd describe like this:

```
  char greeting = 'h';
```

"greeting" is a variable declared as a char. It's not an array and it can hold only one value. It's not a pointer. It's been initialized to the value 'h'. Its size is one byte.  

Here's some examples on the second one:

```
  char greetings[6] = "hello"; 
```

This declares greetings as an array of chars, with size 6. The size is known because we specified it manually. The array's first 5 elements will contain h,e,l,l,o respectively, and the 6th will contain a null terminator. The string literal "hello" "silently includes" a null terminator.

The variable named "greetings" without array index brackets is a pointer to the memory reserved for greetings[0], which contains 'h'.

```
  char greetings[] = "hello";
```

Exactly like the previous example, except the compiler will calculate the size of the array for you, based on the size of the literal you're initializing it with. It will be 5 letters + null terminator = 6 chars.

```
 char greetings[6];
```

Greetings is an array of chars of size 6 (specified manually). All of its elements are uninitialized, but there is space reserved for their values in memory. The variable name "greetings" without array index brackets represents a pointer to the memory reserved for greetings[0], which is uninitialized.

Helps?

**Comment by ghost** [comment]
So char greeting = 'h' , 
Would not be expressed by saying that the value 'h' is initialized to the variable greeting at "address" provided to greeting. ( I do not see one using address in the above explanation of char greeting...is there a reason why ?)

I guess I am still not sure the purpose of the pointer. Will look into it. 
When does C implicitly use pointers( under present content), yet at other aspects just initializes as in the single char greeting.

**Comment by johnwfinigan** [comment]
Almost -- you would say that char greeting is a variable of type char which is initialized to 'h', or, in other words, the variable greeting has value 'h' after that initialization.

When the type in question is a so-called "scalar type", such as an int, a float, or a char, you do not have to reference it using a pointer, although it does have an address where its value is stored, and so you _can_ calculate a pointer to it with the &.  The "variable name" of a scalar type will evaluate to its value when you use it in an expression. So, if you say:

```
  int a = 2;
  int b = a; 
```

Then b will be initialized to 2, because a evaluated to the value previously stored in a.

**BUT**, arrays are "derived" types. In simple terms, they're collections of scalar types like ints and floats. For arrays, their names represent a pointer to their first element. So, it's a true statement to say:

```
  int a[2] = { 4, 5 };

  a == &a[0]      (this evaluates to true)

  a[1] == 4         (this is also true)
```

So, an array is a different kind of type than a char is (scalar vs. derived), and for an array, the array's name is a pointer, and we have special syntax, the square brackets, to access a value in the array, given that pointer.

**Comment by johnwfinigan** [comment]
Also, to address the question of what is a pointer versus an int or a float:

ints and floats are specifically called "arithmetic types", they store a value that is a number.

pointers are their own category of type. They store memory addresses. These addresses can point to any object in memory, including an int or a float or some other arithmetic type.
