### ISSUE TITLE
Hmwk 3 - char *d_to_open = " . ";

### ISSUE THREAD

**Issue by ghost** [johnwfinigan/CSCI2467-Fall2015#6]
There was a question in class regarding this, however, I do not recall the answer.

How does " . " represent a directory name to open ?

Or are we to see this as that what needs to be modified ?

**Comment by johnwfinigan** [comment]
You can read "." as "the C string literal containing one character, a dot"

In this context the dot is an alias for "the directory  we're currently in", which is the running program's current working directory, which here is going to be the directory it was started in.

First let's define a _pathname_ as "a sequence of directory names and file names separated by slashes, that let us find a file on our system".  So `/home/you/myprogram.c` is a pathname leading to a file called `myprogram.c`.

When a program (including your shell) is running, it has a current working directory, and so-called _relative_ pathnames are resolved relative to that working directory. 

For instance if your current working directory is `/home/you` , then saying `ls myprogram.c` will work, since ls looks for `myprogram.c` _relative_ to the current working directory.

Now here's what one of the POSIX standards says about `.` and `..`:

```
  http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap04.html#tag_04_12

  Each filename in the pathname is located in the directory specified by its predecessor
   (for example, in the pathname fragment a/b, file b is located in directory a).

  The special filename dot shall refer to the directory specified by its predecessor. 
  The special filename dot-dot shall refer to the parent directory of its predecessor 
  directory. As a special case, in the root directory, dot-dot may refer to the root 
  directory itself.
```

Notice that these definitions mean that parsing any pathname, if your current working directory is `/home/you` then `/home/you/.` refers to it's predecessor, `/home/you` and so `.` just aliases to the current working directory in this case. If you tried `..`, it's `/home/you/..` relative to the current working directory, and that resolves to the "parent of the predecessor", `/home`.

`...` doesn't mean anything special, although it's a valid filename, and neither does `....`, etc.
