### ISSUE TITLE
Expected Owner Name and Owner Group Name

### ISSUE THREAD

**Issue by ghost** [johnwfinigan/CSCI2467-Fall2015#9]
I am working on the recent hmwk.
I have output for the Owner name and Group Name, using : 
                  pwd->pw_name and grp->gr_name               

```
             That output is drdantin, for owner and group name. 
```

(Teminal Output)
Group Name: drdantin
mode: 100664, name: DamonDantin_Hmwk3.c
Owner Name: drdantin
Group Name: drdantin
mode: 40775, name: Directory
Owner Name: drdantin
Group Name: drdantin
mode: 100775, name: a.out
.......etc

Does this look right to you ?

Thank you.

**Comment by johnwfinigan** [comment]
Yes, that's expected if you are on cook. The reason is simply that you are the owner of your files.

Watch out though that the output for one file should be all on one line, like my example. This is a unix custom mainly because if a command outputs multi-line records, it's output is a pain to parse when used as the input of some other tool
